# version: '3.8'
# services:
#   dev-database:
#     image: postgres:16.0
#     container_name: dev-database
#     ports:
#       - 5432:5432
#     environment:
#       - POSTGRES_USER=postgres
#       - POSTGRES_PASSWORD=postgres
#       - POSTGRES_DB=training
#     networks:
#       - nestjs-networks

# networks:
#   nestjs-networks:
#     driver: bridge
